customhost = "employee.cjm4mau4yzdg.us-east-1.rds.amazonaws.com"
customuser = "empprojectadmin"
custompass = "**********"
customdb = "employee"
custombucket = "dataemployee"
customregion = "us-east-1"
